//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bunniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bunny
    {
        public Bunny()
        {
            this.Meals = new HashSet<Meal>();
        }
    
        public int BunnyID { get; set; }
        public string BunnyName { get; set; }
        public int ShipID { get; set; }
    
        public virtual Ship Ship { get; set; }
        public virtual ICollection<Meal> Meals { get; set; }
    }
}
