//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bunniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodGathered
    {
        public System.Guid FoodID { get; set; }
        public System.Guid VisitID { get; set; }
        public double Quantity { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Visit Visit { get; set; }
    }
}
