//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bunniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.Cargoes = new HashSet<Cargo>();
            this.FoodGathereds = new HashSet<FoodGathered>();
            this.Meals = new HashSet<Meal>();
        }
    
        public int FoodID { get; set; }
        public string FoodName { get; set; }
    
        public virtual ICollection<Cargo> Cargoes { get; set; }
        public virtual ICollection<FoodGathered> FoodGathereds { get; set; }
        public virtual ICollection<Meal> Meals { get; set; }
    }
}
