//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bunniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public int MealID { get; set; }
        public int BunnyID { get; set; }
        public int FoodID { get; set; }
        public double FoodQuantity { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Bunny Bunny { get; set; }
        public virtual Food Food { get; set; }
    }
}
