//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bunniverse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planet
    {
        public Planet()
        {
            this.Ships = new HashSet<Ship>();
            this.Visits = new HashSet<Visit>();
        }
    
        public System.Guid PlanetID { get; set; }
        public string PlanetName { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public double Z { get; set; }
    
        public virtual ICollection<Ship> Ships { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
