//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bunniverse
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Ship
    {
        public Ship()
        {
            this.Bunnies = new HashSet<Bunny>();
            this.Cargoes = new HashSet<Cargo>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int ShipID { get; set; }

        [DataMember]
        public string ShipName { get; set; }

        [DataMember]
        public double EnginePower { get; set; }

        [DataMember]
        public Nullable<int> CurrentPlanetID { get; set; }

        [DataMember]
        public virtual ICollection<Bunny> Bunnies { get; set; }

        [DataMember]
        public virtual ICollection<Cargo> Cargoes { get; set; }

        [DataMember]
        public virtual Planet Planet { get; set; }

        [DataMember]
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
