#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the FluentMappingGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using Telerik.OpenAccess.Metadata.Relational;

namespace Bunniverse.Data
{

	public partial class MySqlEntitiesMetadataSource : FluentMetadataSource
	{
		
		protected override IList<MappingConfiguration> PrepareMapping()
		{
            List<MappingConfiguration> mappingConfigurations = new List<MappingConfiguration>();

            var shipsTravelsMaping = new MappingConfiguration<ShipsTravel>();
            shipsTravelsMaping.MapType(travels => new
            {
                ShipID = travels.ID,
                ShipName = travels.ShipName,
                TotalDistance = travels.TotalDistance,
                PlanetsVisited = travels.PlanetsVisited,
                TotalFoodGathered = travels.TotalFoodGathered
            }).ToTable("ShipsTravel");
            shipsTravelsMaping.HasProperty(s => s.ID).IsIdentity();

            mappingConfigurations.Add(shipsTravelsMaping);

            return mappingConfigurations;
		}
		
		protected override void SetContainerSettings(MetadataContainer container)
		{
			container.Name = "MySqlEntities";
			container.DefaultNamespace = "Bunniverse.Data";
			container.NameGenerator.SourceStrategy = Telerik.OpenAccess.Metadata.NamingSourceStrategy.Property;
			container.NameGenerator.RemoveCamelCase = false;
		}
	}
}
#pragma warning restore 1591
